# Generated by Django 4.2.6 on 2023-10-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default='2023-10-19T20:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(default='2023-10-19T21:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_notific',
            field=models.BooleanField(default=False),
        ),
    ]
